# Generated by Django 3.0.6 on 2020-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='teg',
            field=models.ManyToManyField(null=True, to='portfolio.Teg'),
        ),
    ]
