# Generated by Django 3.0.6 on 2020-05-16 17:58

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('portfolio', '0007_auto_20200516_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='teg',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Teg',
        ),
    ]
